import type { Metadata } from "next";
import "../../globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { NimishMadan } from "@/data/NimishMadan";

export const metadata: Metadata = {
  title: "Nimish Madan | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div
        className={`antialiased text-black bg-white dark:text-white dark:bg-black font-sans`}
      >
        <Navbar data={NimishMadan.Intro} />
        {children}
        <Footer data={NimishMadan.Footer} />
      </div>
  );
}
