import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
    title: "Your Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`antialiased text-white bg-black font-sans`}
            >
                <nav className="flex sm:h-16 py-5 sticky top-0 justify-center sm:px-8 lg:px-32 bg-black z-10">
                    <p className=" nav-logo" >
                        Let's create your portfolio
                    </p>
                </nav>
                {children}
            </body>
        </html>
    );
}
